version: '3.8'

services:
  gui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_DATABASE=influx
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PASSWORD=admin
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=admin
      - NS3_HOST=192.168.100.21


  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    command: sh -c "influxd & sleep 10 && influx -database influx -execute 'delete from /\w*/'; tail -f /dev/null"
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: {}
